Blog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog.Models
{
    public class Post
    {
        public int PostId { get; set; }
        [Required]
        public string Titulo { get; set; }
        [Required]
        public string Corpo { get; set; }
        public List<Comentario> Comentarios { get; set; }
    }
}

Blog/Areas/api/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Blog.Models;

namespace Blog.Areas.api.Controllers
{
    public class PostController : ApiController
    {
        private BlogContext db = new BlogContext();

        // GET api/Post
        public IEnumerable<Post> GetPosts()
        {
            return db.Posts.AsEnumerable();
        }

        // GET api/Post/5
        public Post GetPost(int id)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return post;
        }

        // PUT api/Post/5
        public HttpResponseMessage PutPost(int id, Post post)
        {
            if (ModelState.IsValid && id == post.PostId)
            {
                db.Entry(post).State = EntityState.Modified;

                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // POST api/Post
        public HttpResponseMessage PostPost(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, post);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = post.PostId }));
                return response;
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // DELETE api/Post/5
        public HttpResponseMessage DeletePost(int id)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.Posts.Remove(post);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, post);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    public class ComentarioController : Controller
    {
        private BlogContext db = new BlogContext();

        //
        // GET: /Comentario/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Comentario/Create

        [HttpPost]
        public ActionResult Create(ComentarioDTO comentario)
        {
            if (ModelState.IsValid)
            {
                var novoNovocomentario = new Comentario { Texto = comentario.Texto, 
                Post = db.Posts.Find(comentario.PostId)};
                db.Comentarios.Add(novoNovocomentario);
                db.SaveChanges();
                return RedirectToAction("Details", "Post", new { id = comentario.PostId });
            }

            return View(comentario);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models;

namespace Blog.Controllers
{
    [Authorize(Roles="Admin")]
    public class PostController : Controller
    {
        private BlogContext db = new BlogContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Include(p => p.Comentarios).FirstOrDefault(p => p.PostId == id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog/Views/Post/Create.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.EditorFor(model => model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Post/Delete.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Corpo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Corpo)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog/Views/Post/Details.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Details";
}

@section scripts {
    @Scripts.Render("~/bundle/jquery")
    <script type="text/javascript">
        $(document).ready(function () {
            $(":submit").on('click', function (event) {
                event.stopImmediatePropagation();
                var form = $(this).closest('form');
                $.ajax({
                    url: '/api/Comentario',
                    type: 'POST',
                    data: form.serialize(),
                    dataType: 'json',
                    success: function (comentario) {
                        $("div.comentario").last().after("<div class='comentario'>" + comentario.Texto + "</div>");
                        form[0].reset();
                    }
                });
                return false;
            });
        })
    </script>
}

@Html.DisplayFor(model => model)

<div id="comentarios">
    <p>Comentários:</p>
    @foreach (var comentario in Model.Comentarios)
    {
        <div class="comentario">
            @comentario.Texto
        </div>
    }
    @using (Html.BeginForm("Create", "Comentario", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.PostId)
        @Html.Partial("_CreateComentario", new Blog.Models.Comentario())

        <input type="submit" value="Adicionar Comentario">
    }

</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PostId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog/Views/Post/Edit.cshtml
@model Blog.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.PostId)

        @Html.EditorFor(model => model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog/Views/Post/Index.cshtml
@model IEnumerable<Blog.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@foreach (var item in Model) {
    @Html.DisplayFor(_ => item)
}

</table>